### PR TITLE
Add "persist.intel.statusbar.hidden" to control the statusbar

### PR DESCRIPTION
**Pull request by shellyxxxie**
Add "persist.intel.statusbar.hidden" to control statusbar

### CODE REVIEW

**Comment by shellyxxxie** [comment]
Add "persist.intel.statusbar.hidden" to control statusbar

**Comment by shellyxxxie** [comment]
@walterx-yan, please review  this commit.

**Comment by shellyxxxie** [comment]
@walterx-yan, please review this commit.

**Review by walterx-yan — APPROVED** [review]
ok

**Comment by shellyxxxie** [comment]
@hongcheng.xie@intel.com, please review this commit.

**Pull request closed without merging**
